import { Router } from 'express';
import { getSessionsStatus, register } from '../controllers/sessions.controller.js';
import { loginUser, currentUser, logoutUser } from '../controllers/auth.controller.js';
import passport from '../config/passport.config.js';
const router = Router();
router.get('/', getSessionsStatus);
router.post('/register', passport.authenticate('register', { session: false }), register);
router.post('/login', passport.authenticate('login', { session: false }), loginUser);
router.get('/current', passport.authenticate('current', { session: false }), currentUser);
router.post('/logout', logoutUser);
export default router;
